# @spec_file: .agentforge/specs/core-harness-v1.yaml
# @spec_id: core-harness-v1
# @component_id: core-harness-monitor_domain
# @test_path: tests/unit/harness/test_monitor_domain.py

# Generated by AgentForge
# Spec: agent_monitor
# Phase: green
# Date: 2025-12-31 05:35:32 UTC

from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class ObservationType(Enum):
    ACTION = "action"
    OUTPUT = "output"
    VERIFICATION = "verification"
    STATE_CHANGE = "state_change"
    ERROR = "error"


@dataclass
class Observation:
    type: ObservationType
    timestamp: datetime
    data: dict
    context: str | None = None


class HealthStatus(Enum):
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    CRITICAL = "critical"


class Recommendation(Enum):
    CONTINUE = "continue"
    CHECKPOINT = "checkpoint"
    ESCALATE = "escalate"
    ABORT = "abort"


@dataclass
class LoopDetection:
    detected: bool
    pattern: str | None = None
    count: int = 0
    observations: list[Observation] = None

    def __post_init__(self):
        if self.observations is None:
            self.observations = []


@dataclass
class ThrashingDetection:
    detected: bool
    pattern: str | None = None
    affected_files: list[str] = None
    alternation_count: int = 0

    def __post_init__(self):
        if self.affected_files is None:
            self.affected_files = []


@dataclass
class AgentHealth:
    status: HealthStatus
    issues: list[str]
    recommendation: Recommendation
    loop_detection: LoopDetection | None = None
    thrashing_detection: ThrashingDetection | None = None
    drift_score: float = 0.0
    context_pressure: float = 0.0
    progress_score: float = 0.0
