# @spec_file: .agentforge/specs/core-harness-v1.yaml
# @spec_id: core-harness-v1
# @component_id: core-harness-recovery_domain
# @test_path: tests/unit/harness/test_checkpoint_manager.py

# Generated by AgentForge
# Spec: recovery_strategies
# Phase: green
# Date: 2025-12-31 06:47:35 UTC

"""Domain entities for recovery operations."""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class RecoveryAction(Enum):
    """Types of recovery actions."""
    CHECKPOINT = "checkpoint"
    ROLLBACK = "rollback"
    SUMMARIZE = "summarize"
    RESET = "reset"
    ESCALATE = "escalate"
    RETRY = "retry"
    SKIP = "skip"


class RecoveryResult(Enum):
    """Outcome of a recovery attempt."""
    SUCCESS = "success"
    PARTIAL = "partial"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class Checkpoint:
    """Saved state snapshot."""
    id: str
    timestamp: datetime
    session_id: str
    phase: str
    state: dict
    file_backups: list[str]
    description: str | None = None


@dataclass
class RecoveryAttempt:
    """Record of a recovery operation."""
    action: RecoveryAction
    timestamp: datetime
    trigger: str
    result: RecoveryResult
    details: dict | None = None
    error: str | None = None


@dataclass
class RecoveryPolicy:
    """Rules for when to apply recovery actions."""
    name: str
    triggers: list[str]
    actions: list[RecoveryAction]
    max_attempts: int = 3
    cooldown_seconds: int = 60
