# @spec_file: .agentforge/specs/core-harness-v1.yaml
# @spec_id: core-harness-v1
# @component_id: core-harness-tool_selector
# @test_path: tests/unit/harness/test_tool_selector.py

# Generated by AgentForge
# Spec: tool_selector
# Phase: green
# Date: 2025-12-31 05:26:33 UTC

from pathlib import Path

from .tool_domain import ToolDefinition
from .tool_registry import ToolRegistry


class ToolSelector:
    """Main selector that composes tools for a given context."""

    def __init__(self, registry: ToolRegistry, project_domain: str | None = None):
        """Initialize selector with registry."""
        self.registry = registry
        self.project_domain = project_domain

    def get_tools(self, workflow: str, phase: str, domain: str | None = None) -> list[ToolDefinition]:
        """Get tools for a workflow/phase/domain combination.

        1. Get base tools (always available)
        2. Get phase tools from profile
        3. Get domain tools if domain specified
        4. Get custom tools if any registered
        5. Deduplicate by name (phase overrides base)
        6. Return combined list
        """
        tool_names = set()
        tools = []

        # 1. Get base tools (always available)
        base_tools = self.registry.get_base_tools()
        for tool in base_tools:
            tool_names.add(tool.name)
            tools.append(tool)

        # 2. Get phase tools from profile
        profile = self.registry.get_profile(workflow, phase)
        if profile:
            for tool_name in profile.tools:
                tool = self.registry.get_tool(tool_name)
                if tool:
                    if tool_name in tool_names:
                        # Phase overrides base - remove base tool first
                        tools = [t for t in tools if t.name != tool_name]
                    tool_names.add(tool_name)
                    tools.append(tool)

        # 3. Get domain tools if domain specified
        if domain:
            domain_tools = self.registry.get_domain_tools(domain)
            if domain_tools:
                for tool_name in domain_tools.tools:
                    if tool_name not in tool_names:
                        tool = self.registry.get_tool(tool_name)
                        if tool:
                            tool_names.add(tool_name)
                            tools.append(tool)

        return tools

    def _detect_python(self, project_path: Path) -> bool:
        """Check for Python project indicators."""
        python_files = [
            project_path / "pyproject.toml",
            project_path / "requirements.txt",
            project_path / "setup.py"
        ]
        if any(f.exists() for f in python_files):
            return True
        return any(project_path.glob("**/*.py"))

    def _detect_dotnet(self, project_path: Path) -> bool:
        """Check for .NET project indicators."""
        return any(project_path.glob("**/*.csproj")) or any(project_path.glob("**/*.sln"))

    def _detect_typescript(self, project_path: Path) -> bool:
        """Check for TypeScript project indicators."""
        if (project_path / "tsconfig.json").exists():
            return True
        if any(project_path.glob("**/*.ts")) or any(project_path.glob("**/*.tsx")):
            return True

        package_json = project_path / "package.json"
        if package_json.exists():
            try:
                import json
                with open(package_json) as f:
                    data = json.load(f)
                    deps = data.get("dependencies", {})
                    dev_deps = data.get("devDependencies", {})
                    if "typescript" in deps or "typescript" in dev_deps:
                        return True
            except (OSError, json.JSONDecodeError):
                pass
        return False

    def detect_domain(self, project_path: Path) -> str | None:
        """Auto-detect project domain from codebase."""
        if not project_path.exists() or not project_path.is_dir():
            return None

        if self._detect_python(project_path):
            return "python"
        if self._detect_dotnet(project_path):
            return "dotnet"
        if self._detect_typescript(project_path):
            return "typescript"

        return None

    def get_tool_names(self, workflow: str, phase: str, domain: str | None = None) -> list[str]:
        """Get just tool names for a context (for lighter payloads)."""
        tools = self.get_tools(workflow, phase, domain)
        return [tool.name for tool in tools]

    def validate_tool_access(self, tool_name: str, workflow: str, phase: str) -> bool:
        """Check if a tool is allowed in current context."""
        available_tools = self.get_tool_names(workflow, phase, self.project_domain)
        return tool_name in available_tools
