# @spec_file: .agentforge/specs/core-harness-v1.yaml
# @spec_id: core-harness-v1
# @component_id: core-harness-tool_domain
# @test_path: tests/unit/harness/test_tool_registry.py

# Generated by AgentForge
# Spec: tool_selector
# Phase: green
# Date: 2025-12-31 05:25:49 UTC

"""Domain entities for tool definitions and profiles."""

from dataclasses import dataclass
from typing import Any


@dataclass
class ToolDefinition:
    """Definition of a single tool available to agents."""

    name: str
    description: str
    parameters: dict[str, Any]
    category: str
    handler: str | None = None
    requires_approval: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary for API response."""
        return {
            'name': self.name,
            'description': self.description,
            'parameters': self.parameters,
            'category': self.category,
            'handler': self.handler,
            'requires_approval': self.requires_approval
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> 'ToolDefinition':
        """Deserialize from dictionary."""
        return cls(
            name=data['name'],
            description=data['description'],
            parameters=data['parameters'],
            category=data['category'],
            handler=data.get('handler'),
            requires_approval=data.get('requires_approval', False)
        )


@dataclass
class ToolProfile:
    """Collection of tools for a specific workflow phase."""

    workflow: str
    phase: str
    tools: list[str]
    description: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        result = {
            'workflow': self.workflow,
            'phase': self.phase,
            'tools': self.tools
        }
        if self.description is not None:
            result['description'] = self.description
        return result

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> 'ToolProfile':
        """Deserialize from dictionary."""
        return cls(
            workflow=data['workflow'],
            phase=data['phase'],
            tools=data['tools'],
            description=data.get('description')
        )


@dataclass
class DomainTools:
    """Domain-specific tool set (Python, .NET, TypeScript)."""

    domain: str
    tools: list[str]
    detection_patterns: list[str]

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            'domain': self.domain,
            'tools': self.tools,
            'detection_patterns': self.detection_patterns
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> 'DomainTools':
        """Deserialize from dictionary."""
        return cls(
            domain=data['domain'],
            tools=data['tools'],
            detection_patterns=data['detection_patterns']
        )
