# @spec_file: .agentforge/specs/cli-click-commands-v1.yaml
# @spec_id: cli-click-commands-v1
# @component_id: cli-click_commands-bridge
# @test_path: tests/unit/tools/bridge/test_registry.py

"""
Bridge CLI Commands
===================

CLI commands for the Profile-to-Conformance Bridge.

Commands:
- bridge generate: Generate contracts from profile
- bridge preview: Preview what would be generated
- bridge mappings: List available pattern mappings
- bridge refresh: Regenerate contracts from updated profile
"""

import sys
import click
from pathlib import Path


@click.group('bridge', help='Profile-to-Conformance Bridge commands')
def bridge():
    """Bridge commands for generating contracts from discovered patterns."""
    pass


@bridge.command('generate')
@click.option('--path', '-p', type=click.Path(exists=True), default='.',
              help='Root path to analyze (default: current directory)')
@click.option('--profile', type=click.Path(exists=True),
              help='Path to codebase_profile.yaml')
@click.option('--output-dir', '-o', default='contracts',
              help='Output directory for contracts (default: contracts/)')
@click.option('--zone', '-z', type=str,
              help='Generate for specific zone only')
@click.option('--confidence', '-c', type=float, default=0.6,
              help='Minimum confidence threshold (default: 0.6)')
@click.option('--dry-run', is_flag=True,
              help='Preview without writing files')
@click.option('--force', '-f', is_flag=True,
              help='Overwrite existing contracts')
@click.option('--verbose', '-v', is_flag=True,
              help='Verbose output')
def generate(path, profile, output_dir, zone, confidence, dry_run, force, verbose):
    """
    Generate contracts from codebase profile.

    Reads the codebase_profile.yaml generated by 'agentforge discover'
    and creates enforceable contract YAML files based on detected patterns.

    Examples:
        agentforge bridge generate
        agentforge bridge generate --dry-run
        agentforge bridge generate --zone core-service
        agentforge bridge generate --confidence 0.8
    """
    from agentforge.cli.commands.bridge import run_bridge_generate

    run_bridge_generate(
        root_path=Path(path),
        profile_path=Path(profile) if profile else None,
        output_dir=output_dir,
        zone_filter=zone,
        confidence_threshold=confidence,
        dry_run=dry_run,
        force=force,
        verbose=verbose,
    )


@bridge.command('preview')
@click.option('--path', '-p', type=click.Path(exists=True), default='.',
              help='Root path to analyze')
@click.option('--profile', type=click.Path(exists=True),
              help='Path to codebase_profile.yaml')
@click.option('--zone', '-z', type=str,
              help='Preview specific zone only')
@click.option('--verbose', '-v', is_flag=True,
              help='Verbose output')
def preview(path, profile, zone, verbose):
    """
    Preview what contracts would be generated.

    Shows the checks that would be generated without writing any files.

    Examples:
        agentforge bridge preview
        agentforge bridge preview --zone core-service
    """
    from agentforge.cli.commands.bridge import run_bridge_preview

    run_bridge_preview(
        root_path=Path(path),
        profile_path=Path(profile) if profile else None,
        zone_filter=zone,
        verbose=verbose,
    )


@bridge.command('mappings')
@click.option('--pattern', type=str,
              help='Filter by pattern key')
@click.option('--format', '-f', 'output_format',
              type=click.Choice(['table', 'yaml', 'json']), default='table',
              help='Output format')
def mappings(pattern, output_format):
    """
    List available pattern-to-check mappings.

    Shows all registered mappings that transform discovered patterns
    into conformance checks.

    Examples:
        agentforge bridge mappings
        agentforge bridge mappings --pattern cqrs
        agentforge bridge mappings --format yaml
    """
    from agentforge.cli.commands.bridge import run_bridge_mappings

    run_bridge_mappings(pattern_filter=pattern, output_format=output_format)


@bridge.command('refresh')
@click.option('--path', '-p', type=click.Path(exists=True), default='.',
              help='Root path to analyze')
@click.option('--profile', type=click.Path(exists=True),
              help='Path to codebase_profile.yaml')
@click.option('--zone', '-z', type=str,
              help='Refresh specific zone only')
@click.option('--verbose', '-v', is_flag=True,
              help='Verbose output')
def refresh(path, profile, zone, verbose):
    """
    Regenerate contracts from updated profile.

    Use after running 'agentforge discover' to update contracts
    based on newly discovered patterns.

    Examples:
        agentforge bridge refresh
        agentforge bridge refresh --zone core-service
    """
    from agentforge.cli.commands.bridge import run_bridge_refresh

    run_bridge_refresh(
        root_path=Path(path),
        profile_path=Path(profile) if profile else None,
        zone_filter=zone,
        verbose=verbose,
    )


@bridge.command('diff')
@click.option('--path', '-p', type=click.Path(exists=True), default='.',
              help='Root path to analyze')
@click.option('--zone', '-z', type=str,
              help='Diff specific zone only')
def diff(path, zone):
    """
    Show diff between generated and existing contracts.

    Compares what would be generated to what currently exists.
    """
    from agentforge.cli.commands.bridge import run_bridge_diff

    run_bridge_diff(root_path=Path(path), zone_filter=zone)
