# @spec_file: .agentforge/specs/harness-v1.yaml
# @spec_id: harness-v1
# @component_id: tools-harness-orchestrator_domain
# @test_path: tests/unit/harness/test_agent_orchestrator.py

# Generated by AgentForge
# Spec: agent_orchestrator
# Phase: green
# Date: 2025-12-31

"""Domain entities for agent orchestration."""

from datetime import datetime
from enum import Enum
from typing import Optional
from dataclasses import dataclass, field


class OrchestratorState(Enum):
    """Current state of the orchestrator."""
    IDLE = "idle"
    RUNNING = "running"
    PAUSED = "paused"
    RECOVERING = "recovering"
    WAITING_FOR_HUMAN = "waiting_for_human"
    COMPLETED = "completed"
    FAILED = "failed"


class ExecutionMode(Enum):
    """How much human oversight is required."""
    AUTONOMOUS = "autonomous"
    SUPERVISED = "supervised"
    INTERACTIVE = "interactive"


@dataclass
class AgentTask:
    """A unit of work for the agent."""
    id: str
    description: str
    context: dict
    created_at: datetime
    priority: int = 0
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    status: str = "pending"


@dataclass
class ExecutionResult:
    """Result of an agent execution step."""
    task_id: str
    success: bool
    output: Optional[str]
    error: Optional[str]
    duration_seconds: float
    tools_used: list[str]
    tokens_consumed: int = 0


@dataclass
class OrchestratorConfig:
    """Configuration for orchestrator behavior."""
    execution_mode: ExecutionMode = ExecutionMode.AUTONOMOUS
    max_iterations: int = 100
    health_check_interval: int = 10
    auto_checkpoint: bool = True
    checkpoint_interval: int = 20
    recovery_enabled: bool = True
    escalation_enabled: bool = True
