# @spec_file: .agentforge/specs/harness-v1.yaml
# @spec_id: harness-v1
# @component_id: tools-harness-tool_domain
# @test_path: tests/unit/harness/test_tool_registry.py

# Generated by AgentForge
# Spec: tool_selector
# Phase: green
# Date: 2025-12-31 05:25:49 UTC

"""Domain entities for tool definitions and profiles."""

from dataclasses import dataclass, field
from typing import Optional, Dict, List, Any


@dataclass
class ToolDefinition:
    """Definition of a single tool available to agents."""
    
    name: str
    description: str
    parameters: Dict[str, Any]
    category: str
    handler: Optional[str] = None
    requires_approval: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary for API response."""
        return {
            'name': self.name,
            'description': self.description,
            'parameters': self.parameters,
            'category': self.category,
            'handler': self.handler,
            'requires_approval': self.requires_approval
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ToolDefinition':
        """Deserialize from dictionary."""
        return cls(
            name=data['name'],
            description=data['description'],
            parameters=data['parameters'],
            category=data['category'],
            handler=data.get('handler'),
            requires_approval=data.get('requires_approval', False)
        )


@dataclass
class ToolProfile:
    """Collection of tools for a specific workflow phase."""
    
    workflow: str
    phase: str
    tools: List[str]
    description: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        result = {
            'workflow': self.workflow,
            'phase': self.phase,
            'tools': self.tools
        }
        if self.description is not None:
            result['description'] = self.description
        return result
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ToolProfile':
        """Deserialize from dictionary."""
        return cls(
            workflow=data['workflow'],
            phase=data['phase'],
            tools=data['tools'],
            description=data.get('description')
        )


@dataclass
class DomainTools:
    """Domain-specific tool set (Python, .NET, TypeScript)."""
    
    domain: str
    tools: List[str]
    detection_patterns: List[str]
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            'domain': self.domain,
            'tools': self.tools,
            'detection_patterns': self.detection_patterns
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'DomainTools':
        """Deserialize from dictionary."""
        return cls(
            domain=data['domain'],
            tools=data['tools'],
            detection_patterns=data['detection_patterns']
        )
