# Generated by AgentForge
# Spec: recovery_strategies
# Phase: red
# Date: 2025-12-31 06:44:38 UTC

"""
Tests for recovery domain entities.
These tests verify the structure and behavior of recovery domain objects
including enums, data classes, and their validation logic.
"""

from datetime import datetime

from agentforge.core.harness.recovery_domain import (
    Checkpoint,
    RecoveryAction,
    RecoveryAttempt,
    RecoveryPolicy,
    RecoveryResult,
)


class TestRecoveryAction:
    """Test RecoveryAction enum values and behavior."""

    def test_recovery_action_has_all_required_values(self):
        """Test that RecoveryAction enum contains all specified values."""
        expected_values = {
            'CHECKPOINT',
            'ROLLBACK',
            'SUMMARIZE',
            'RESET',
            'ESCALATE',
            'RETRY',
            'SKIP'
        }
        actual_values = {action.name for action in RecoveryAction}
        assert actual_values == expected_values, "Expected actual_values to equal expected_values"

    def test_recovery_action_values_are_accessible(self):
        """Test that individual RecoveryAction values can be accessed."""
        assert RecoveryAction.CHECKPOINT, "Expected RecoveryAction.CHECKPOINT to be truthy"
        assert RecoveryAction.ROLLBACK, "Expected RecoveryAction.ROLLBACK to be truthy"
        assert RecoveryAction.SUMMARIZE, "Expected RecoveryAction.SUMMARIZE to be truthy"
        assert RecoveryAction.RESET, "Expected RecoveryAction.RESET to be truthy"
        assert RecoveryAction.ESCALATE, "Expected RecoveryAction.ESCALATE to be truthy"
        assert RecoveryAction.RETRY, "Expected RecoveryAction.RETRY to be truthy"
        assert RecoveryAction.SKIP, "Expected RecoveryAction.SKIP to be truthy"


class TestRecoveryResult:
    """Test RecoveryResult enum values and behavior."""

    def test_recovery_result_has_all_required_values(self):
        """Test that RecoveryResult enum contains all specified values."""
        expected_values = {
            'SUCCESS',
            'PARTIAL',
            'FAILED',
            'SKIPPED'
        }
        actual_values = {result.name for result in RecoveryResult}
        assert actual_values == expected_values, "Expected actual_values to equal expected_values"

    def test_recovery_result_values_are_accessible(self):
        """Test that individual RecoveryResult values can be accessed."""
        assert RecoveryResult.SUCCESS, "Expected RecoveryResult.SUCCESS to be truthy"
        assert RecoveryResult.PARTIAL, "Expected RecoveryResult.PARTIAL to be truthy"
        assert RecoveryResult.FAILED, "Expected RecoveryResult.FAILED to be truthy"
        assert RecoveryResult.SKIPPED, "Expected RecoveryResult.SKIPPED to be truthy"


class TestCheckpoint:
    """Test Checkpoint entity structure and behavior."""

    def test_checkpoint_creation_with_required_fields(self):
        """Test creating a Checkpoint with all required fields."""
        timestamp = datetime.now()
        checkpoint = Checkpoint(
            id="test-checkpoint-1",
            timestamp=timestamp,
            session_id="session-123",
            phase="planning",
            state={"key": "value"},
            file_backups=["/path/to/backup1.txt", "/path/to/backup2.txt"]
        )

        assert checkpoint.id == "test-checkpoint-1", "Expected checkpoint.id to equal 'test-checkpoint-1'"
        assert checkpoint.timestamp == timestamp, "Expected checkpoint.timestamp to equal timestamp"
        assert checkpoint.session_id == "session-123", "Expected checkpoint.session_id to equal 'session-123'"
        assert checkpoint.phase == "planning", "Expected checkpoint.phase to equal 'planning'"
        assert checkpoint.state == {"key": "value"}, "Expected checkpoint.state to equal {'key': 'value'}"
        assert checkpoint.file_backups == ["/path/to/backup1.txt", "/path/to/backup2.txt"], "Expected checkpoint.file_backups to equal ['/path/to/backup1.txt', '/..."
        assert checkpoint.description is None, "Expected checkpoint.description is None"

    def test_checkpoint_creation_with_optional_description(self):
        """Test creating a Checkpoint with optional description field."""
        checkpoint = Checkpoint(
            id="test-checkpoint-2",
            timestamp=datetime.now(),
            session_id="session-456",
            phase="execution",
            state={},
            file_backups=[],
            description="Before risky operation"
        )

        assert checkpoint.description == "Before risky operation", "Expected checkpoint.description to equal 'Before risky operation'"

    def test_checkpoint_state_can_be_complex_dict(self):
        """Test that Checkpoint state field can hold complex nested data."""
        complex_state = {
            "variables": {"x": 1, "y": 2},
            "context": ["item1", "item2"],
            "nested": {"deep": {"value": True}}
        }

        checkpoint = Checkpoint(
            id="complex-checkpoint",
            timestamp=datetime.now(),
            session_id="session-789",
            phase="analysis",
            state=complex_state,
            file_backups=[]
        )

        assert checkpoint.state == complex_state, "Expected checkpoint.state to equal complex_state"

    def test_checkpoint_file_backups_can_be_empty_list(self):
        """Test that Checkpoint can have empty file_backups list."""
        checkpoint = Checkpoint(
            id="no-files-checkpoint",
            timestamp=datetime.now(),
            session_id="session-empty",
            phase="start",
            state={},
            file_backups=[]
        )

        assert checkpoint.file_backups == [], "Expected checkpoint.file_backups to equal []"


class TestRecoveryAttempt:
    """Test RecoveryAttempt entity structure and behavior."""

    def test_recovery_attempt_creation_with_required_fields(self):
        """Test creating a RecoveryAttempt with required fields."""
        timestamp = datetime.now()
        attempt = RecoveryAttempt(
            action=RecoveryAction.CHECKPOINT,
            timestamp=timestamp,
            trigger="loop detected",
            result=RecoveryResult.SUCCESS
        )

        assert attempt.action == RecoveryAction.CHECKPOINT, "Expected attempt.action to equal RecoveryAction.CHECKPOINT"
        assert attempt.timestamp == timestamp, "Expected attempt.timestamp to equal timestamp"
        assert attempt.trigger == "loop detected", "Expected attempt.trigger to equal 'loop detected'"
        assert attempt.result == RecoveryResult.SUCCESS, "Expected attempt.result to equal RecoveryResult.SUCCESS"
        assert attempt.details is None, "Expected attempt.details is None"
        assert attempt.error is None, "Expected attempt.error is None"

    def test_recovery_attempt_creation_with_optional_fields(self):
        """Test creating a RecoveryAttempt with optional details and error."""
        attempt = RecoveryAttempt(
            action=RecoveryAction.ROLLBACK,
            timestamp=datetime.now(),
            trigger="drift detected",
            result=RecoveryResult.FAILED,
            details={"checkpoint_id": "cp-123", "files_restored": 3},
            error="Failed to restore file: permission denied"
        )

        assert attempt.details == {"checkpoint_id": "cp-123", "files_restored": 3}, "Expected attempt.details to equal {'checkpoint_id': 'cp-123',..."
        assert attempt.error == "Failed to restore file: permission denied", "Expected attempt.error to equal 'Failed to restore file: pe..."

    def test_recovery_attempt_supports_all_action_types(self):
        """Test that RecoveryAttempt can be created with all RecoveryAction types."""
        for action in RecoveryAction:
            attempt = RecoveryAttempt(
                action=action,
                timestamp=datetime.now(),
                trigger="test trigger",
                result=RecoveryResult.SUCCESS
            )
            assert attempt.action == action, "Expected attempt.action to equal action"

    def test_recovery_attempt_supports_all_result_types(self):
        """Test that RecoveryAttempt can be created with all RecoveryResult types."""
        for result in RecoveryResult:
            attempt = RecoveryAttempt(
                action=RecoveryAction.RETRY,
                timestamp=datetime.now(),
                trigger="test trigger",
                result=result
            )
            assert attempt.result == result, "Expected attempt.result to equal result"


class TestRecoveryPolicy:
    """Test RecoveryPolicy entity structure and behavior."""

    def test_recovery_policy_creation_with_required_fields(self):
        """Test creating a RecoveryPolicy with required fields."""
        policy = RecoveryPolicy(
            name="test_policy",
            triggers=["loop", "drift"],
            actions=[RecoveryAction.CHECKPOINT, RecoveryAction.ROLLBACK]
        )

        assert policy.name == "test_policy", "Expected policy.name to equal 'test_policy'"
        assert policy.triggers == ["loop", "drift"], "Expected policy.triggers to equal ['loop', 'drift']"
        assert policy.actions == [RecoveryAction.CHECKPOINT, RecoveryAction.ROLLBACK], "Expected policy.actions to equal [RecoveryAction.CHECKPOINT,..."
        assert policy.max_attempts == 3, "Expected policy.max_attempts to equal 3"# default value
        assert policy.cooldown_seconds == 60, "Expected policy.cooldown_seconds to equal 60"# default value

    def test_recovery_policy_creation_with_custom_defaults(self):
        """Test creating a RecoveryPolicy with custom max_attempts and cooldown."""
        policy = RecoveryPolicy(
            name="custom_policy",
            triggers=["thrashing"],
            actions=[RecoveryAction.RESET],
            max_attempts=5,
            cooldown_seconds=120
        )

        assert policy.max_attempts == 5, "Expected policy.max_attempts to equal 5"
        assert policy.cooldown_seconds == 120, "Expected policy.cooldown_seconds to equal 120"

    def test_recovery_policy_supports_multiple_triggers(self):
        """Test that RecoveryPolicy can handle multiple trigger conditions."""
        triggers = [
            "loop detected",
            "Loop detected",
            "Repeated action",
            "circular behavior"
        ]

        policy = RecoveryPolicy(
            name="multi_trigger_policy",
            triggers=triggers,
            actions=[RecoveryAction.CHECKPOINT]
        )

        assert policy.triggers == triggers, "Expected policy.triggers to equal triggers"

    def test_recovery_policy_supports_multiple_actions(self):
        """Test that RecoveryPolicy can handle multiple recovery actions."""
        actions = [
            RecoveryAction.CHECKPOINT,
            RecoveryAction.SUMMARIZE,
            RecoveryAction.ROLLBACK,
            RecoveryAction.ESCALATE
        ]

        policy = RecoveryPolicy(
            name="multi_action_policy",
            triggers=["complex issue"],
            actions=actions
        )

        assert policy.actions == actions, "Expected policy.actions to equal actions"

    def test_recovery_policy_empty_triggers_list(self):
        """Test that RecoveryPolicy can be created with empty triggers list."""
        policy = RecoveryPolicy(
            name="no_triggers_policy",
            triggers=[],
            actions=[RecoveryAction.ESCALATE]
        )

        assert policy.triggers == [], "Expected policy.triggers to equal []"

    def test_recovery_policy_single_action(self):
        """Test that RecoveryPolicy can be created with single action."""
        policy = RecoveryPolicy(
            name="single_action_policy",
            triggers=["critical error"],
            actions=[RecoveryAction.ESCALATE]
        )

        assert len(policy.actions) == 1, "Expected len(policy.actions) to equal 1"
        assert policy.actions[0] == RecoveryAction.ESCALATE, "Expected policy.actions[0] to equal RecoveryAction.ESCALATE"

    def test_recovery_policy_max_attempts_custom_value(self):
        """Test that RecoveryPolicy accepts custom max_attempts value."""
        policy = RecoveryPolicy(
            name="valid_policy",
            triggers=["test"],
            actions=[RecoveryAction.RETRY],
            max_attempts=1
        )
        assert policy.max_attempts == 1, "Expected policy.max_attempts to equal 1"

        # Zero attempts is technically allowed (caller's responsibility)
        policy_zero = RecoveryPolicy(
            name="zero_policy",
            triggers=["test"],
            actions=[RecoveryAction.RETRY],
            max_attempts=0
        )
        assert policy_zero.max_attempts == 0, "Expected policy_zero.max_attempts to equal 0"

    def test_recovery_policy_cooldown_custom_value(self):
        """Test that RecoveryPolicy accepts custom cooldown_seconds value."""
        policy = RecoveryPolicy(
            name="valid_policy",
            triggers=["test"],
            actions=[RecoveryAction.RETRY],
            cooldown_seconds=0
        )
        assert policy.cooldown_seconds == 0, "Expected policy.cooldown_seconds to equal 0"

        # Large cooldown
        policy_large = RecoveryPolicy(
            name="large_cooldown_policy",
            triggers=["test"],
            actions=[RecoveryAction.RETRY],
            cooldown_seconds=3600
        )
        assert policy_large.cooldown_seconds == 3600, "Expected policy_large.cooldown_seconds to equal 3600"
