# @spec_file: .agentforge/specs/core-harness-v1.yaml
# @spec_id: core-harness-v1
# @component_id: tools-harness-monitor_domain
# @impl_path: tools/harness/monitor_domain.py

# Generated by AgentForge
# Spec: agent_monitor
# Phase: red
# Date: 2025-12-31 05:34:01 UTC

"""Tests for monitor domain entities."""

from datetime import datetime

from agentforge.core.harness.monitor_domain import (
    AgentHealth,
    HealthStatus,
    LoopDetection,
    Observation,
    ObservationType,
    Recommendation,
    ThrashingDetection,
)


class TestObservationType:
    """Test ObservationType enum."""

    def test_observation_type_has_all_required_values(self):
        """Test that ObservationType enum has all required values."""
        assert ObservationType.ACTION
        assert ObservationType.OUTPUT
        assert ObservationType.VERIFICATION
        assert ObservationType.STATE_CHANGE
        assert ObservationType.ERROR


class TestObservation:
    """Test Observation entity."""

    def test_observation_creation_with_required_fields(self):
        """Test creating observation with required fields."""
        timestamp = datetime.now()
        data = {"action": "test_action"}

        obs = Observation(
            type=ObservationType.ACTION,
            timestamp=timestamp,
            data=data
        )

        assert obs.type == ObservationType.ACTION
        assert obs.timestamp == timestamp
        assert obs.data == data
        assert obs.context is None

    def test_observation_creation_with_context(self):
        """Test creating observation with optional context."""
        obs = Observation(
            type=ObservationType.ERROR,
            timestamp=datetime.now(),
            data={"error": "test error"},
            context="During file processing"
        )

        assert obs.context == "During file processing"


class TestHealthStatus:
    """Test HealthStatus enum."""

    def test_health_status_has_all_required_values(self):
        """Test that HealthStatus enum has all required values."""
        assert HealthStatus.HEALTHY
        assert HealthStatus.DEGRADED
        assert HealthStatus.CRITICAL


class TestRecommendation:
    """Test Recommendation enum."""

    def test_recommendation_has_all_required_values(self):
        """Test that Recommendation enum has all required values."""
        assert Recommendation.CONTINUE
        assert Recommendation.CHECKPOINT
        assert Recommendation.ESCALATE
        assert Recommendation.ABORT


class TestLoopDetection:
    """Test LoopDetection entity."""

    def test_loop_detection_creation_not_detected(self):
        """Test creating LoopDetection when no loop detected."""
        detection = LoopDetection(
            detected=False,
            pattern=None,
            count=0,
            observations=[]
        )

        assert detection.detected is False
        assert detection.pattern is None
        assert detection.count == 0
        assert detection.observations == []

    def test_loop_detection_creation_detected(self):
        """Test creating LoopDetection when loop detected."""
        obs = Observation(
            type=ObservationType.ACTION,
            timestamp=datetime.now(),
            data={"action": "repeat"}
        )

        detection = LoopDetection(
            detected=True,
            pattern="Repeated action: repeat",
            count=3,
            observations=[obs, obs, obs]
        )

        assert detection.detected is True
        assert detection.pattern == "Repeated action: repeat"
        assert detection.count == 3
        assert len(detection.observations) == 3


class TestThrashingDetection:
    """Test ThrashingDetection entity."""

    def test_thrashing_detection_creation_not_detected(self):
        """Test creating ThrashingDetection when no thrashing detected."""
        detection = ThrashingDetection(
            detected=False,
            pattern=None,
            affected_files=[],
            alternation_count=0
        )

        assert detection.detected is False
        assert detection.pattern is None
        assert detection.affected_files == []
        assert detection.alternation_count == 0

    def test_thrashing_detection_creation_detected(self):
        """Test creating ThrashingDetection when thrashing detected."""
        detection = ThrashingDetection(
            detected=True,
            pattern="File modification thrashing",
            affected_files=["test.py", "config.json"],
            alternation_count=4
        )

        assert detection.detected is True
        assert detection.pattern == "File modification thrashing"
        assert detection.affected_files == ["test.py", "config.json"]
        assert detection.alternation_count == 4


class TestAgentHealth:
    """Test AgentHealth entity."""

    def test_agent_health_creation_healthy(self):
        """Test creating AgentHealth for healthy agent."""
        health = AgentHealth(
            status=HealthStatus.HEALTHY,
            issues=[],
            recommendation=Recommendation.CONTINUE,
            loop_detection=None,
            thrashing_detection=None,
            drift_score=0.1,
            context_pressure=0.3,
            progress_score=0.8
        )

        assert health.status == HealthStatus.HEALTHY
        assert health.issues == []
        assert health.recommendation == Recommendation.CONTINUE
        assert health.loop_detection is None
        assert health.thrashing_detection is None
        assert health.drift_score == 0.1
        assert health.context_pressure == 0.3
        assert health.progress_score == 0.8

    def test_agent_health_creation_critical_with_detections(self):
        """Test creating AgentHealth for critical agent with detections."""
        loop_detection = LoopDetection(
            detected=True,
            pattern="Action loop",
            count=5,
            observations=[]
        )

        thrashing_detection = ThrashingDetection(
            detected=True,
            pattern="File thrashing",
            affected_files=["main.py"],
            alternation_count=6
        )

        health = AgentHealth(
            status=HealthStatus.CRITICAL,
            issues=["Loop detected", "Thrashing detected", "High drift"],
            recommendation=Recommendation.ABORT,
            loop_detection=loop_detection,
            thrashing_detection=thrashing_detection,
            drift_score=0.8,
            context_pressure=0.95,
            progress_score=0.05
        )

        assert health.status == HealthStatus.CRITICAL
        assert len(health.issues) == 3
        assert health.recommendation == Recommendation.ABORT
        assert health.loop_detection.detected is True
        assert health.thrashing_detection.detected is True
        assert health.drift_score == 0.8
        assert health.context_pressure == 0.95
        assert health.progress_score == 0.05
