# Generated by AgentForge
# Spec: tool_selector
# Phase: red
# Date: 2025-12-31 05:25:17 UTC

"""Tests for tool domain entities."""

import pytest
from tools.harness.tool_domain import ToolDefinition, ToolProfile, DomainTools


class TestToolDefinition:
    """Test ToolDefinition entity."""

    def test_init_with_required_fields_creates_instance(self):
        """Test that ToolDefinition can be created with required fields."""
        tool = ToolDefinition(
            name="test_tool",
            description="A test tool",
            parameters={"param1": {"type": "string"}},
            category="test"
        )
        
        assert tool.name == "test_tool"
        assert tool.description == "A test tool"
        assert tool.parameters == {"param1": {"type": "string"}}
        assert tool.category == "test"
        assert tool.handler is None
        assert tool.requires_approval is False

    def test_init_with_all_fields_creates_instance(self):
        """Test that ToolDefinition can be created with all fields."""
        tool = ToolDefinition(
            name="test_tool",
            description="A test tool",
            parameters={"param1": {"type": "string"}},
            handler="test.handler",
            requires_approval=True,
            category="test"
        )
        
        assert tool.name == "test_tool"
        assert tool.description == "A test tool"
        assert tool.parameters == {"param1": {"type": "string"}}
        assert tool.handler == "test.handler"
        assert tool.requires_approval is True
        assert tool.category == "test"

    def test_to_dict_returns_serialized_data(self):
        """Test that to_dict returns proper dictionary representation."""
        tool = ToolDefinition(
            name="test_tool",
            description="A test tool",
            parameters={"param1": {"type": "string"}},
            handler="test.handler",
            requires_approval=True,
            category="test"
        )
        
        result = tool.to_dict()
        
        expected = {
            "name": "test_tool",
            "description": "A test tool",
            "parameters": {"param1": {"type": "string"}},
            "handler": "test.handler",
            "requires_approval": True,
            "category": "test"
        }
        assert result == expected

    def test_from_dict_creates_instance_from_data(self):
        """Test that from_dict creates ToolDefinition from dictionary."""
        data = {
            "name": "test_tool",
            "description": "A test tool",
            "parameters": {"param1": {"type": "string"}},
            "handler": "test.handler",
            "requires_approval": True,
            "category": "test"
        }
        
        tool = ToolDefinition.from_dict(data)
        
        assert tool.name == "test_tool"
        assert tool.description == "A test tool"
        assert tool.parameters == {"param1": {"type": "string"}}
        assert tool.handler == "test.handler"
        assert tool.requires_approval is True
        assert tool.category == "test"

    def test_from_dict_with_minimal_data_uses_defaults(self):
        """Test that from_dict uses default values for optional fields."""
        data = {
            "name": "test_tool",
            "description": "A test tool",
            "parameters": {},
            "category": "test"
        }
        
        tool = ToolDefinition.from_dict(data)
        
        assert tool.name == "test_tool"
        assert tool.handler is None
        assert tool.requires_approval is False


class TestToolProfile:
    """Test ToolProfile entity."""

    def test_init_with_required_fields_creates_instance(self):
        """Test that ToolProfile can be created with required fields."""
        profile = ToolProfile(
            workflow="test_workflow",
            phase="test_phase",
            tools=["tool1", "tool2"]
        )
        
        assert profile.workflow == "test_workflow"
        assert profile.phase == "test_phase"
        assert profile.tools == ["tool1", "tool2"]
        assert profile.description is None

    def test_init_with_all_fields_creates_instance(self):
        """Test that ToolProfile can be created with all fields."""
        profile = ToolProfile(
            workflow="test_workflow",
            phase="test_phase",
            tools=["tool1", "tool2"],
            description="Test profile"
        )
        
        assert profile.workflow == "test_workflow"
        assert profile.phase == "test_phase"
        assert profile.tools == ["tool1", "tool2"]
        assert profile.description == "Test profile"

    def test_to_dict_returns_serialized_data(self):
        """Test that to_dict returns proper dictionary representation."""
        profile = ToolProfile(
            workflow="test_workflow",
            phase="test_phase",
            tools=["tool1", "tool2"],
            description="Test profile"
        )
        
        result = profile.to_dict()
        
        expected = {
            "workflow": "test_workflow",
            "phase": "test_phase",
            "tools": ["tool1", "tool2"],
            "description": "Test profile"
        }
        assert result == expected

    def test_from_dict_creates_instance_from_data(self):
        """Test that from_dict creates ToolProfile from dictionary."""
        data = {
            "workflow": "test_workflow",
            "phase": "test_phase",
            "tools": ["tool1", "tool2"],
            "description": "Test profile"
        }
        
        profile = ToolProfile.from_dict(data)
        
        assert profile.workflow == "test_workflow"
        assert profile.phase == "test_phase"
        assert profile.tools == ["tool1", "tool2"]
        assert profile.description == "Test profile"


class TestDomainTools:
    """Test DomainTools entity."""

    def test_init_creates_instance_with_all_fields(self):
        """Test that DomainTools can be created with all fields."""
        domain_tools = DomainTools(
            domain="python",
            tools=["pytest", "ruff"],
            detection_patterns=["*.py", "pyproject.toml"]
        )
        
        assert domain_tools.domain == "python"
        assert domain_tools.tools == ["pytest", "ruff"]
        assert domain_tools.detection_patterns == ["*.py", "pyproject.toml"]
