# Generated by AgentForge
# Spec: tool_selector
# Phase: red
# Date: 2025-12-31 05:23:05 UTC

"""
Tests for tool domain entities.

These tests verify the behavior of ToolDefinition, ToolProfile, and DomainTools
entities that represent the core domain model for tool selection.
"""

import pytest
from typing import Optional

from tools.harness.tool_domain import ToolDefinition, ToolProfile, DomainTools


class TestToolDefinition:
    """Test cases for ToolDefinition entity."""

    def test_tool_definition_init_with_required_fields_creates_instance(self):
        """Test that ToolDefinition can be created with required fields."""
        # Arrange
        name = "file_read"
        description = "Read contents of a file"
        parameters = {"path": {"type": "string"}}
        category = "file"

        # Act
        tool = ToolDefinition(
            name=name,
            description=description,
            parameters=parameters,
            category=category
        )

        # Assert
        assert tool.name == name
        assert tool.description == description
        assert tool.parameters == parameters
        assert tool.category == category
        assert tool.handler is None
        assert tool.requires_approval is False

    def test_tool_definition_init_with_all_fields_creates_instance(self):
        """Test that ToolDefinition can be created with all fields."""
        # Arrange
        name = "deploy_app"
        description = "Deploy application to production"
        parameters = {"environment": {"type": "string"}}
        handler = "deployment.deploy_handler"
        requires_approval = True
        category = "deployment"

        # Act
        tool = ToolDefinition(
            name=name,
            description=description,
            parameters=parameters,
            handler=handler,
            requires_approval=requires_approval,
            category=category
        )

        # Assert
        assert tool.name == name
        assert tool.description == description
        assert tool.parameters == parameters
        assert tool.handler == handler
        assert tool.requires_approval is True
        assert tool.category == category

    def test_tool_definition_to_dict_returns_serialized_data(self):
        """Test that to_dict returns proper dictionary representation."""
        # Arrange
        tool = ToolDefinition(
            name="test_tool",
            description="A test tool",
            parameters={"param1": {"type": "string"}},
            handler="test.handler",
            requires_approval=True,
            category="test"
        )

        # Act
        result = tool.to_dict()

        # Assert
        expected = {
            "name": "test_tool",
            "description": "A test tool",
            "parameters": {"param1": {"type": "string"}},
            "handler": "test.handler",
            "requires_approval": True,
            "category": "test"
        }
        assert result == expected

    def test_tool_definition_to_dict_with_none_handler_excludes_handler(self):
        """Test that to_dict excludes None handler from output."""
        # Arrange
        tool = ToolDefinition(
            name="test_tool",
            description="A test tool",
            parameters={},
            category="test"
        )

        # Act
        result = tool.to_dict()

        # Assert
        assert "handler" not in result or result["handler"] is None

    def test_tool_definition_from_dict_creates_instance(self):
        """Test that from_dict creates ToolDefinition from dictionary."""
        # Arrange
        data = {
            "name": "file_write",
            "description": "Write content to file",
            "parameters": {"path": {"type": "string"}, "content": {"type": "string"}},
            "handler": "file.write_handler",
            "requires_approval": False,
            "category": "file"
        }

        # Act
        tool = ToolDefinition.from_dict(data)

        # Assert
        assert tool.name == "file_write"
        assert tool.description == "Write content to file"
        assert tool.parameters == data["parameters"]
        assert tool.handler == "file.write_handler"
        assert tool.requires_approval is False
        assert tool.category == "file"

    def test_tool_definition_from_dict_with_minimal_data_uses_defaults(self):
        """Test that from_dict uses default values for missing fields."""
        # Arrange
        data = {
            "name": "minimal_tool",
            "description": "Minimal tool",
            "parameters": {},
            "category": "test"
        }

        # Act
        tool = ToolDefinition.from_dict(data)

        # Assert
        assert tool.name == "minimal_tool"
        assert tool.description == "Minimal tool"
        assert tool.parameters == {}
        assert tool.handler is None
        assert tool.requires_approval is False
        assert tool.category == "test"

    def test_tool_definition_from_dict_with_missing_required_field_raises_error(self):
        """Test that from_dict raises error when required field is missing."""
        # Arrange
        data = {
            "name": "incomplete_tool",
            "description": "Missing category",
            "parameters": {}
            # Missing required 'category' field
        }

        # Act & Assert
        with pytest.raises(KeyError):
            ToolDefinition.from_dict(data)


class TestToolProfile:
    """Test cases for ToolProfile entity."""

    def test_tool_profile_init_with_required_fields_creates_instance(self):
        """Test that ToolProfile can be created with required fields."""
        # Arrange
        workflow = "tdflow"
        phase = "red"
        tools = ["file_read", "write_test", "run_test"]

        # Act
        profile = ToolProfile(
            workflow=workflow,
            phase=phase,
            tools=tools
        )

        # Assert
        assert profile.workflow == workflow
        assert profile.phase == phase
        assert profile.tools == tools
        assert profile.description is None

    def test_tool_profile_init_with_description_creates_instance(self):
        """Test that ToolProfile can be created with description."""
        # Arrange
        workflow = "spec"
        phase = "intake"
        tools = ["file_read", "directory_list"]
        description = "Initial project analysis phase"

        # Act
        profile = ToolProfile(
            workflow=workflow,
            phase=phase,
            tools=tools,
            description=description
        )

        # Assert
        assert profile.workflow == workflow
        assert profile.phase == phase
        assert profile.tools == tools
        assert profile.description == description

    def test_tool_profile_to_dict_returns_serialized_data(self):
        """Test that to_dict returns proper dictionary representation."""
        # Arrange
        profile = ToolProfile(
            workflow="tdflow",
            phase="green",
            tools=["file_read", "write_code", "run_test"],
            description="Implementation phase"
        )

        # Act
        result = profile.to_dict()

        # Assert
        expected = {
            "workflow": "tdflow",
            "phase": "green",
            "tools": ["file_read", "write_code", "run_test"],
            "description": "Implementation phase"
        }
        assert result == expected

    def test_tool_profile_to_dict_with_none_description_excludes_description(self):
        """Test that to_dict excludes None description from output."""
        # Arrange
        profile = ToolProfile(
            workflow="spec",
            phase="draft",
            tools=["file_read", "write_markdown"]
        )

        # Act
        result = profile.to_dict()

        # Assert
        assert "description" not in result or result["description"] is None

    def test_tool_profile_from_dict_creates_instance(self):
        """Test that from_dict creates ToolProfile from dictionary."""
        # Arrange
        data = {
            "workflow": "spec",
            "phase": "validate",
            "tools": ["conformance_check", "write_yaml"],
            "description": "Validation phase"
        }

        # Act
        profile = ToolProfile.from_dict(data)

        # Assert
        assert profile.workflow == "spec"
        assert profile.phase == "validate"
        assert profile.tools == ["conformance_check", "write_yaml"]
        assert profile.description == "Validation phase"

    def test_tool_profile_from_dict_with_minimal_data_uses_defaults(self):
        """Test that from_dict uses default values for missing optional fields."""
        # Arrange
        data = {
            "workflow": "custom",
            "phase": "build",
            "tools": ["compile", "package"]
        }

        # Act
        profile = ToolProfile.from_dict(data)

        # Assert
        assert profile.workflow == "custom"
        assert profile.phase == "build"
        assert profile.tools == ["compile", "package"]
        assert profile.description is None

    def test_tool_profile_from_dict_with_missing_required_field_raises_error(self):
        """Test that from_dict raises error when required field is missing."""
        # Arrange
        data = {
            "workflow": "incomplete",
            "tools": ["some_tool"]
            # Missing required 'phase' field
        }

        # Act & Assert
        with pytest.raises(KeyError):
            ToolProfile.from_dict(data)


class TestDomainTools:
    """Test cases for DomainTools entity."""

    def test_domain_tools_init_creates_instance(self):
        """Test that DomainTools can be created with all fields."""
        # Arrange
        domain = "python"
        tools = ["pytest", "ruff_check", "mypy"]
        detection_patterns = ["pyproject.toml", "*.py", "requirements.txt"]

        # Act
        domain_tools = DomainTools(
            domain=domain,
            tools=tools,
            detection_patterns=detection_patterns
        )

        # Assert
        assert domain_tools.domain == domain
        assert domain_tools.tools == tools
        assert domain_tools.detection_patterns == detection_patterns

    def test_domain_tools_init_with_empty_lists_creates_instance(self):
        """Test that DomainTools can be created with empty tool and pattern lists."""
        # Arrange
        domain = "unknown"
        tools = []
        detection_patterns = []

        # Act
        domain_tools = DomainTools(
            domain=domain,
            tools=tools,
            detection_patterns=detection_patterns
        )

        # Assert
        assert domain_tools.domain == domain
        assert domain_tools.tools == []
        assert domain_tools.detection_patterns == []

    def test_domain_tools_with_dotnet_domain_stores_correct_data(self):
        """Test that DomainTools correctly stores .NET domain data."""
        # Arrange
        domain = "dotnet"
        tools = ["dotnet_build", "dotnet_test", "dotnet_format"]
        detection_patterns = ["*.csproj", "*.sln", "*.cs"]

        # Act
        domain_tools = DomainTools(
            domain=domain,
            tools=tools,
            detection_patterns=detection_patterns
        )

        # Assert
        assert domain_tools.domain == "dotnet"
        assert "dotnet_build" in domain_tools.tools
        assert "dotnet_test" in domain_tools.tools
        assert "dotnet_format" in domain_tools.tools
        assert "*.csproj" in domain_tools.detection_patterns
        assert "*.sln" in domain_tools.detection_patterns
        assert "*.cs" in domain_tools.detection_patterns

    def test_domain_tools_with_typescript_domain_stores_correct_data(self):
        """Test that DomainTools correctly stores TypeScript domain data."""
        # Arrange
        domain = "typescript"
        tools = ["npm_test", "eslint", "prettier"]
        detection_patterns = ["package.json", "tsconfig.json", "*.ts", "*.tsx"]

        # Act
        domain_tools = DomainTools(
            domain=domain,
            tools=tools,
            detection_patterns=detection_patterns
        )

        # Assert
        assert domain_tools.domain == "typescript"
        assert "npm_test" in domain_tools.tools
        assert "eslint" in domain_tools.tools
        assert "prettier" in domain_tools.tools
        assert "package.json" in domain_tools.detection_patterns
        assert "tsconfig.json" in domain_tools.detection_patterns
        assert "*.ts" in domain_tools.detection_patterns
        assert "*.tsx" in domain_tools.detection_patterns
